// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// check_openmp_enabled
bool check_openmp_enabled();
RcppExport SEXP _splikit_check_openmp_enabled() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(check_openmp_enabled());
    return rcpp_result_gen;
END_RCPP
}
// silhouette_avg
double silhouette_avg(const arma::mat& X, const IntegerVector& cluster_assignments, int n_threads);
RcppExport SEXP _splikit_silhouette_avg(SEXP XSEXP, SEXP cluster_assignmentsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type cluster_assignments(cluster_assignmentsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(silhouette_avg(X, cluster_assignments, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// calcDeviances_ratio
arma::vec calcDeviances_ratio(const arma::sp_mat& M1, const arma::sp_mat& M2, int num_threads);
RcppExport SEXP _splikit_calcDeviances_ratio(SEXP M1SEXP, SEXP M2SEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type M1(M1SEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type M2(M2SEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(calcDeviances_ratio(M1, M2, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// cppBetabinPseudoR2
NumericVector cppBetabinPseudoR2(const arma::mat& Z, const arma::mat& m1, const arma::mat& m2);
RcppExport SEXP _splikit_cppBetabinPseudoR2(SEXP ZSEXP, SEXP m1SEXP, SEXP m2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type m2(m2SEXP);
    rcpp_result_gen = Rcpp::wrap(cppBetabinPseudoR2(Z, m1, m2));
    return rcpp_result_gen;
END_RCPP
}
// calcNBDeviancesWithThetaEstimation
arma::vec calcNBDeviancesWithThetaEstimation(const arma::sp_mat& gene_expression);
RcppExport SEXP _splikit_calcNBDeviancesWithThetaEstimation(SEXP gene_expressionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type gene_expression(gene_expressionSEXP);
    rcpp_result_gen = Rcpp::wrap(calcNBDeviancesWithThetaEstimation(gene_expression));
    return rcpp_result_gen;
END_RCPP
}
// standardizeSparse_variance_vst
NumericVector standardizeSparse_variance_vst(SEXP matSEXP, bool display_progress);
RcppExport SEXP _splikit_standardizeSparse_variance_vst(SEXP matSEXPSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type matSEXP(matSEXPSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(standardizeSparse_variance_vst(matSEXP, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// rowVariance_cpp
NumericVector rowVariance_cpp(SEXP mat);
RcppExport SEXP _splikit_rowVariance_cpp(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(rowVariance_cpp(mat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_splikit_check_openmp_enabled", (DL_FUNC) &_splikit_check_openmp_enabled, 0},
    {"_splikit_silhouette_avg", (DL_FUNC) &_splikit_silhouette_avg, 3},
    {"_splikit_calcDeviances_ratio", (DL_FUNC) &_splikit_calcDeviances_ratio, 3},
    {"_splikit_cppBetabinPseudoR2", (DL_FUNC) &_splikit_cppBetabinPseudoR2, 3},
    {"_splikit_calcNBDeviancesWithThetaEstimation", (DL_FUNC) &_splikit_calcNBDeviancesWithThetaEstimation, 1},
    {"_splikit_standardizeSparse_variance_vst", (DL_FUNC) &_splikit_standardizeSparse_variance_vst, 2},
    {"_splikit_rowVariance_cpp", (DL_FUNC) &_splikit_rowVariance_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_splikit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
