#' @useDynLib splikit, .registration = TRUE
#' @importFrom Rcpp evalCpp
#' @importFrom methods as
#' @importFrom stats na.omit
NULL

# Declare global variables used in data.table operations to avoid R CMD check NOTEs
utils::globalVariables(c("unique_mapped", "i", "j", "x_1", "x_tot", "x_2", "group_id", "ID"))

#' Compute Pseudo-Correlation Using Beta-Binomial Model
#'
#' This function calculates a pseudo R²-like correlation metric using a beta-binomial model
#' implemented in C++. It takes in a data matrix `ZDB_matrix` and two model matrices
#' for inclusion and exclusion, respectively. The function now supports both sparse and dense
#' matrices for m1 and m2, and allows selection between Cox-Snell and Nagelkerke R² metrics.
#'
#' @param ZDB_matrix A numeric dense matrix of shape (events x samples). Should have rownames representing events.
#' @param m1_inclusion A numeric matrix (dense or sparse) of the same number of rows as `ZDB_matrix`, representing inclusion features.
#' @param m2_exclusion A numeric matrix (dense or sparse) of the same number of rows as `ZDB_matrix`, representing exclusion features.
#' @param metric Character string specifying which R² metric to compute. Options are "CoxSnell" (default) or "Nagelkerke".
#' @param suppress_warnings Logical. If \code{TRUE} (default), suppresses warnings during computation (e.g., due to ill-conditioned inputs).
#' @param verbose Logical. If \code{TRUE}, prints progress and informational messages. Default is \code{FALSE}.
#' @param permutation_count Integer. Number of times the null model is generated by
#'   permuting the cells (columns) of `ZDB_matrix` and recomputing the pseudo
#'   correlation. Each permutation yields one null value per event, so the n draws
#'   form a per-event empirical null. Defaults to `100L`. Use `1L` to reproduce the
#'   original single-permutation behaviour. Values of 1000 or more are recommended
#'   for reliable empirical FDR estimation (the smallest achievable empirical
#'   p-value is approximately `1 / (permutation_count + 1)`).
#' @param permutation_seed Optional single numeric value. If supplied, the random
#'   number generator is seeded with it before the permutations are drawn, making
#'   the null distribution (and therefore the empirical p-values) reproducible. The
#'   caller's global RNG stream is saved and restored, so passing a seed does not
#'   perturb downstream randomness. Defaults to `NULL` (use the ambient RNG state).
#'
#' @return An S3 object of class `splikit_pseudo_correlation_result` with three
#' components:
#' \describe{
#'   \item{statistics}{A per-event `data.table` with the columns described below.}
#'   \item{null_distribution}{A long `data.table` containing one row per retained
#'   event and permutation, with columns `event`, `permutation`, and
#'   `null_pseudo_correlation`. This table is suitable for direct export or pooled
#'   descriptive analyses; event-level p-values remain based on each event's own
#'   permutation draws.}
#'   \item{metadata}{A list recording the permutation settings and null-draw counts.}
#' }
#' The `statistics` component contains:
#' \describe{
#'   \item{event}{The event names from `ZDB_matrix` rownames.}
#'   \item{pseudo_correlation}{The computed pseudo R² correlation values using the specified metric.}
#'   \item{null_distribution}{Mean of the per-event null correlation values across the `permutation_count` permutations (equal to the single null draw when `permutation_count = 1`).}
#'   \item{null_sd}{Standard deviation of the per-event null draws (`NA` when fewer than two valid draws are available).}
#'   \item{n_perm_valid}{Number of permutations that produced a non-`NA` null value for the event.}
#'   \item{emp_pvalue}{Two-sided empirical p-value, `(b + 1) / (n_perm_valid + 1)`, where `b` is the number of valid null draws whose absolute value is greater than or equal to the absolute observed correlation.}
#'   \item{emp_padj}{Benjamini-Hochberg adjusted `emp_pvalue` across the retained events.}
#' }
#'
#' @examples
#' \donttest{
#' set.seed(42)
#' # get the m1 object
#' junction_abundance_object <- load_toy_SJ_object()
#' m1_obj <- make_m1(junction_ab_object = junction_abundance_object)
#'
#' # obtaining the m1 and eventdata
#' m1_inclusion <- m1_obj$m1_inclusion_matrix
#' eventdata <- m1_obj$event_data
#' m2_exclusion <- make_m2(m1_inclusion, eventdata)
#'
#' # subset to a few hundred cells to keep the example quick
#' cells <- seq_len(min(250, ncol(m1_inclusion)))
#' m1_inclusion <- m1_inclusion[, cells]
#' m2_exclusion <- m2_exclusion[, cells]
#'
#' # creating a dummy ZDB
#' ZDB_matrix <- matrix(rnorm(n = (nrow(m1_inclusion) * ncol(m1_inclusion)), sd = 7),
#' nrow = nrow(m1_inclusion),
#' ncol = ncol(m1_inclusion))
#' rownames(ZDB_matrix) <- rownames(m1_inclusion)
#'
#' # m1 and m2 can now be either sparse or dense matrices
#' # Example with dense matrices (backward compatible)
#' m1_dense <- as.matrix(m1_inclusion)
#' m2_dense <- as.matrix(m2_exclusion)
#' pseudo_r_square_cox <- get_pseudo_correlation(ZDB_matrix, m1_dense, m2_dense,
#'                                               permutation_count = 20,
#'                                               permutation_seed = 1)
#' print(pseudo_r_square_cox)
#'
#' # Example with sparse matrices (more memory efficient)
#' pseudo_r_square_sparse <- get_pseudo_correlation(ZDB_matrix, m1_inclusion, m2_exclusion,
#'                                                  permutation_count = 20,
#'                                                  permutation_seed = 1)
#'
#' # Per-event empirical p-values and the exportable long null distribution
#' head(pseudo_r_square_sparse$statistics[,
#'   c("event", "pseudo_correlation", "emp_pvalue")])
#' dim(pseudo_r_square_sparse$null_distribution)
#'
#' # Example using Nagelkerke R-squared instead of Cox-Snell
#' pseudo_r_square_nagel <- get_pseudo_correlation(ZDB_matrix, m1_inclusion, m2_exclusion,
#'                                                 metric = "Nagelkerke",
#'                                                 permutation_count = 20)
#' print(pseudo_r_square_nagel)
#' }
#'
#' @export
get_pseudo_correlation <- function(ZDB_matrix, m1_inclusion = NULL, m2_exclusion = NULL, metric = "CoxSnell", suppress_warnings = TRUE, verbose = FALSE, permutation_count = 100L, permutation_seed = NULL) {

  # Handle SplikitObject input
  if (inherits(ZDB_matrix, "SplikitObject")) {
    # First arg is SplikitObject, second should be ZDB_matrix
    obj <- ZDB_matrix
    if (is.null(m1_inclusion) || !is.matrix(m1_inclusion)) {
      stop("When using SplikitObject, provide ZDB_matrix as second argument.", call. = FALSE)
    }
    ZDB_matrix <- m1_inclusion
    m1_inclusion <- obj$m1
    m2_exclusion <- obj$m2
    if (is.null(m2_exclusion)) {
      stop("SplikitObject has no M2 matrix. Call obj$makeM2() first.", call. = FALSE)
    }
  }

  # Check m1 and m2 are provided
  if (is.null(m1_inclusion) || is.null(m2_exclusion)) {
    stop("m1_inclusion and m2_exclusion are required.", call. = FALSE)
  }

  # Validate metric parameter
  metric <- match.arg(metric, choices = c("CoxSnell", "Nagelkerke"))

  # Validate permutation controls
  if (!is.numeric(permutation_count) || length(permutation_count) != 1L ||
      is.na(permutation_count) || permutation_count < 1) {
    stop("permutation_count must be a single positive integer.", call. = FALSE)
  }
  permutation_count <- as.integer(permutation_count)

  if (!is.null(permutation_seed) &&
      (!is.numeric(permutation_seed) || length(permutation_seed) != 1L ||
       is.na(permutation_seed))) {
    stop("permutation_seed must be NULL or a single numeric value.", call. = FALSE)
  }

  # Check ZDB_matrix (must be dense)
  if (!is.matrix(ZDB_matrix)) stop("ZDB_matrix must be a dense matrix.")

  # Check m1 and m2 (can be sparse or dense)
  if (!is.matrix(m1_inclusion) && !inherits(m1_inclusion, "Matrix")) {
    stop("m1_inclusion must be either a dense matrix or a sparse Matrix.")
  }
  if (!is.matrix(m2_exclusion) && !inherits(m2_exclusion, "Matrix")) {
    stop("m2_exclusion must be either a dense matrix or a sparse Matrix.")
  }

  if (nrow(m1_inclusion) != nrow(ZDB_matrix)) {
    stop("m1_inclusion must have the same number of rows as ZDB_matrix.")
  }
  if (nrow(m2_exclusion) != nrow(ZDB_matrix)) {
    stop("m2_exclusion must have the same number of rows as ZDB_matrix.")
  }

  if (verbose) message("Input dimension check passed. Proceeding with computation.")

  # Seed the RNG for reproducible permutations without disturbing the caller's
  # global RNG stream (state is saved here and restored on exit).
  if (!is.null(permutation_seed)) {
    if (exists(".Random.seed", envir = globalenv(), inherits = FALSE)) {
      old_seed <- get(".Random.seed", envir = globalenv(), inherits = FALSE)
      on.exit(assign(".Random.seed", old_seed, envir = globalenv()), add = TRUE)
    } else {
      on.exit(
        if (exists(".Random.seed", envir = globalenv(), inherits = FALSE)) {
          rm(".Random.seed", envir = globalenv())
        },
        add = TRUE
      )
    }
    set.seed(permutation_seed)
  }

  # Define the computation function. Returns the observed correlations, the event
  # names, and the matrix of per-event null draws (events x permutation_count).
  run_computation <- function() {
    # Determine which C++ function to call based on matrix types
    is_m1_sparse <- inherits(m1_inclusion, "Matrix")
    is_m2_sparse <- inherits(m2_exclusion, "Matrix")

    # The C++ kernels expect a numeric CSC sparse matrix (dgCMatrix). Coerce
    # integer or non-CSC sparse inputs (e.g. igCMatrix produced when
    # Matrix::Matrix() is called on an integer matrix) before dispatch.
    if (is_m1_sparse && !inherits(m1_inclusion, "dgCMatrix")) {
      m1_inclusion <- methods::as(methods::as(m1_inclusion, "CsparseMatrix"),
                                  "dMatrix")
    }
    if (is_m2_sparse && !inherits(m2_exclusion, "dgCMatrix")) {
      m2_exclusion <- methods::as(methods::as(m2_exclusion, "CsparseMatrix"),
                                  "dMatrix")
    }

    # Dispatch helper: compute the per-event pseudo correlation for a given Z,
    # selecting the kernel that matches the m1/m2 matrix storage types. Shared
    # by the observed pass and every null permutation.
    compute_kernel <- function(Zmat) {
      if (!is_m1_sparse && !is_m2_sparse) {
        cppBetabinPseudoR2(Z = Zmat,
                           m1 = as.matrix(m1_inclusion),
                           m2 = as.matrix(m2_exclusion),
                           metric = metric)
      } else if (is_m1_sparse && is_m2_sparse) {
        cppBetabinPseudoR2_sparse(Z = Zmat,
                                  m1 = m1_inclusion,
                                  m2 = m2_exclusion,
                                  metric = metric)
      } else if (is_m1_sparse && !is_m2_sparse) {
        cppBetabinPseudoR2_mixed1(Z = Zmat,
                                  m1 = m1_inclusion,
                                  m2 = as.matrix(m2_exclusion),
                                  metric = metric)
      } else {
        cppBetabinPseudoR2_mixed2(Z = Zmat,
                                  m1 = as.matrix(m1_inclusion),
                                  m2 = m2_exclusion,
                                  metric = metric)
      }
    }

    # Observed correlation (computed once; independent of the permutations).
    correls <- compute_kernel(ZDB_matrix)

    if (is.null(rownames(ZDB_matrix))) {
      warning("ZDB_matrix has no row names; assigning default event names.")
      events <- paste0("Event_", seq_len(nrow(ZDB_matrix)))
    } else {
      events <- rownames(ZDB_matrix)
    }

    # Null distribution: permute the cells (columns) of Z to break the
    # cell-to-cell pairing with splicing, recompute, and repeat
    # permutation_count times. Each column of null_mat is one permutation.
    n_cells <- ncol(ZDB_matrix)
    null_mat <- matrix(NA_real_, nrow = nrow(ZDB_matrix), ncol = permutation_count)
    for (k in seq_len(permutation_count)) {
      perm_idx <- sample.int(n_cells)
      null_mat[, k] <- compute_kernel(ZDB_matrix[, perm_idx, drop = FALSE])
    }

    list(correls = correls, events = events, null_mat = null_mat)
  }

  # Run computation with or without warning suppression
  if (suppress_warnings) {
    comp <- suppressWarnings(run_computation())
  } else {
    comp <- run_computation()
  }

  correls  <- comp$correls
  events   <- comp$events
  null_mat <- comp$null_mat

  # Per-event null summaries (vectorised over events).
  n_valid <- rowSums(!is.na(null_mat))
  s1 <- rowSums(null_mat, na.rm = TRUE)
  s2 <- rowSums(null_mat^2, na.rm = TRUE)

  null_mean <- s1 / n_valid
  null_mean[n_valid < 1L] <- NA_real_

  null_var <- (s2 - (s1^2) / n_valid) / (n_valid - 1)
  # Clamp tiny negative variances from floating-point cancellation to avoid
  # spurious sqrt() NaN warnings.
  null_var[is.finite(null_var) & null_var < 0] <- 0
  null_sd <- sqrt(null_var)
  null_sd[n_valid < 2L] <- NA_real_

  # Two-sided empirical p-value with the (b + 1) / (m + 1) correction, comparing
  # absolute null draws to the absolute observed correlation. NA observed values
  # and events with no valid null draws yield NA.
  obs_abs <- abs(correls)
  exceed <- rowSums(abs(null_mat) >= obs_abs, na.rm = TRUE)
  emp_pvalue <- (exceed + 1) / (n_valid + 1)
  emp_pvalue[is.na(correls) | n_valid < 1L] <- NA_real_

  results <- data.table::data.table(
    event = events,
    pseudo_correlation = correls,
    null_distribution = null_mean,
    null_sd = null_sd,
    n_perm_valid = as.integer(n_valid),
    emp_pvalue = emp_pvalue
  )

  # Retain events with a valid observed correlation and at least one valid null
  # draw (mirrors the previous na.omit() coupling of observed and null values).
  keep <- !is.na(results$pseudo_correlation) & !is.na(results$null_distribution)
  results <- results[keep, ]
  null_mat <- null_mat[keep, , drop = FALSE]

  # Benjamini-Hochberg adjusted empirical p-values across the retained events.
  results$emp_padj <- stats::p.adjust(results$emp_pvalue, method = "BH")

  # Expose every retained event-by-permutation draw in a long, exportable table.
  # R matrices are column-major, so this ordering groups all retained events for
  # permutation 1, followed by all retained events for permutation 2, and so on.
  null_distribution <- data.table::data.table(
    event = rep(results$event, times = permutation_count),
    permutation = rep(seq_len(permutation_count), each = nrow(results)),
    null_pseudo_correlation = as.vector(null_mat)
  )

  metadata <- list(
    metric = metric,
    permutation_count = permutation_count,
    permutation_seed = permutation_seed,
    n_events_input = nrow(ZDB_matrix),
    n_events_retained = nrow(results),
    n_null_draws = nrow(null_distribution),
    n_null_valid = sum(!is.na(null_distribution$null_pseudo_correlation)),
    pooled_null_usage = "descriptive"
  )

  result <- structure(
    list(
      statistics = results,
      null_distribution = null_distribution,
      metadata = metadata
    ),
    class = c("splikit_pseudo_correlation_result", "list")
  )

  if (verbose) message("Computation completed successfully.")
  return(result)
}

#' Print a pseudo-correlation result
#'
#' Prints a short preview of the per-event statistics and reports the size of
#' the long null distribution without printing every permutation draw.
#'
#' @param x A `splikit_pseudo_correlation_result` object.
#' @param n Number of statistic rows to preview. Defaults to `6L`.
#' @param ... Additional arguments passed to the `data.table` print method.
#'
#' @return `x`, invisibly.
#' @method print splikit_pseudo_correlation_result
#' @export
print.splikit_pseudo_correlation_result <- function(x, n = 6L, ...) {
  if (!is.numeric(n) || length(n) != 1L || is.na(n) || n < 0) {
    stop("n must be a single non-negative integer.", call. = FALSE)
  }
  n <- as.integer(n)

  cat("Pseudo-correlation result\n")
  cat("Statistics:", nrow(x$statistics), "retained event(s)\n")
  print(utils::head(x$statistics, n), ...)
  cat(
    "Null distribution:", nrow(x$null_distribution), "row(s);",
    x$metadata$n_null_valid, "valid draw(s)\n"
  )
  invisible(x)
}

#' Calculate Row-wise Variance for Dense or Sparse Matrices
#'
#' @description
#' Efficiently computes the variance of each row for either a base R dense matrix
#' or a sparse dgCMatrix, via a single Rcpp entry point. Logs progress messages
#' to the R console.
#' @param M A numeric matrix (base R matrix) or a sparse matrix of class \code{"dgCMatrix"}.
#' @param verbose Logical. If \code{TRUE}, prints progress and informational messages. Default is \code{FALSE}.
#' @return A numeric vector of length \code{nrow(M)} containing the variance of each row.
#' @details
#' Dispatches in C++ between dense and sparse implementations to avoid unnecessary
#' overhead or external dependencies. Uses compressed-column traversal for sparse inputs.
#' @examples
#' library(Matrix)
#' # Dense example
#' dm <- matrix(rnorm(1000), nrow = 100)
#' get_rowVar(dm)
#' # Sparse example
#' sm <- rsparsematrix(100, 10, density = 0.1)
#' get_rowVar(sm)
#' @note
#' Only 32-bit integer indices are supported, due to limitations in R's internal matrix representations.
#' This function will not work with matrices that exceed the 32-bit integer indexing range.
#' @export
get_rowVar <- function(M, verbose = FALSE) {
  if (!(is.matrix(M) || inherits(M, "dgCMatrix"))) {
    stop("`M` must be either a dense numeric matrix or a dgCMatrix.")
  }
  if (verbose) message("[get_rowVar] Starting computation")
  result <- rowVariance_cpp(M)
  if (verbose) message("[get_rowVar] Computation finished")
  result
}

#' Compute Average Silhouette Width with Logging
#'
#' Computes the average silhouette width for a clustering solution using Euclidean distance.
#'
#' @param X A numeric matrix where rows are observations and columns are features.
#' @param cluster_assignments An integer vector of cluster assignments, which must be the same length as the number of rows in \code{X}.
#' @param n_threads Number of threads to use for parallel processing.
#' @param verbose Logical. If \code{TRUE}, prints progress and informational messages. Default is \code{FALSE}.
#'
#' @note This process can be very slow for large matrices if single-threaded. Use multiple threads to take advantage of parallel computation for significantly faster results.
#'
#' @return A single numeric value: the average silhouette score.
#'
#' @examples
#' # Preparing the inputs
#' set.seed(42)
#' pc_matrix <- matrix(data = rnorm(n = 10000 * 15, sd = 2), nrow = 10000, ncol = 15)
#' cluster_numbers <- as.integer(runif(n = 10000, min = 1, max = 10))
#'
#' # Getting the mean silhouette score
#' n_threads <- parallel::detectCores()
#' score <- get_silhouette_mean(pc_matrix, cluster_numbers, n_threads)
#' print(score)
#'
#' @export
get_silhouette_mean <- function(X, cluster_assignments, n_threads = 1, verbose = FALSE) {
  stopifnot(is.matrix(X), is.numeric(X))
  stopifnot(is.integer(cluster_assignments) || is.numeric(cluster_assignments))
  stopifnot(nrow(X) == length(cluster_assignments))

  if (verbose) message("[silhouette_avg] Starting computation...")
  if (verbose) message("[silhouette_avg] Using ", n_threads, " threads...")

  score <- silhouette_avg(X, as.integer(cluster_assignments), as.integer(n_threads))
  return(score)
}
