# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

silhouette_avg <- function(X, cluster_assignments, n_threads = 1L) {
    .Call(`_splikit_silhouette_avg`, X, cluster_assignments, n_threads)
}

calcDeviances_ratio <- function(M1, M2) {
    .Call(`_splikit_calcDeviances_ratio`, M1, M2)
}

cppBetabinPseudoR2 <- function(Z, m1, m2) {
    .Call(`_splikit_cppBetabinPseudoR2`, Z, m1, m2)
}

calcNBDeviancesWithThetaEstimation <- function(gene_expression) {
    .Call(`_splikit_calcNBDeviancesWithThetaEstimation`, gene_expression)
}

standardizeSparse_variance_vst <- function(matSEXP, display_progress = FALSE) {
    .Call(`_splikit_standardizeSparse_variance_vst`, matSEXP, display_progress)
}

rowVariance_cpp <- function(mat) {
    .Call(`_splikit_rowVariance_cpp`, mat)
}

